### PR TITLE
Enable pterodactyl packs

### PR DESCRIPTION
**Pull request by Sophtli**
I needed the packs functionality for this API, so I quickly added it myself.
Maybe someone else finds this useful as well.

### CODE REVIEW

**Comment by mattmalec** [comment]
Do you know if there’s a data structure for Packs? I haven’t looked too close into it. I’d rather use that than just a Long.

**Comment by Sophtli** [comment]
I didn't find any data structure for packs in the API but I could have missed it.

**Review by FarmVivi — APPROVED** [review]

**Comment by mattmalec** [comment]
I’m going to take a look sometime this week. I’d love to merge this ASAP.

**Comment by HaedHutner** [comment]
Hi, looking to use this library in my project. Would love to be able to use packs! Do you know when you might be able to look into merging this PR? @mattmalec

**Pull request merged**
