### PR TITLE
Add method to retrieve accurate backup count

### PR DESCRIPTION
**Pull request by Timongcraft**
Add a way to retrieve the backup count accurately, as counting backups can be unreliable due to truncation when there are too many.

### CODE REVIEW

**Comment by mattmalec** [comment]
can you share how you're usually attempting to grab the count today? curious for the use case

**Comment by Timongcraft** [comment]
Example:
I have a Pterodactyl server with 19/20 backups.

```java
ClientServer#retrieveBackups#execute#size
```
returns 15

while
```java
ClientServer#retrieveBackupCount#execute
```
returns 19

Although now I believe this is a bug that should be looked into rather than just adding another method to go around it.
[At the time](https://github.com/Timongcraft/Pterodactyl4J-Maven/commit/48321d93d7235056e9d7e3dc8a11fb41a19f43b6) of writing this fix I was more interested in just getting it to work than fixing bugs.

**Comment by mattmalec** [comment]
ah i see what you're saying. it's not actually a bug, retrieveBackups returns a PaginationPteroAction, so running .execute like that is only grabbing the first page. if you want all the pages you can do ClientServer#retrieveBackups#all#execute

see docs here: https://ci.mattmalec.com/job/Pterodactyl4J/javadoc/com/mattmalec/pterodactyl4j/requests/PaginationAction.html#all()

**Comment by mattmalec** [comment]
you can also increase the max number of entities per page with the [limit](https://ci.mattmalec.com/job/Pterodactyl4J/javadoc/com/mattmalec/pterodactyl4j/requests/PaginationAction.html#limit(int)) method

**Comment by Timongcraft** [comment]
Oh, yeah, that makes sense. I didn't really look into that. Then this should be invalid.

**Pull request closed without merging**
